name: drink_dictionary
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  capitalize: ^0.0.1
  flutter:
    sdk: flutter
  flutter_typeahead: ^4.8.0
  google_fonts: ^5.1.0
  searchfield: ^0.8.7
  substring_highlight: ^1.0.33

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Untitled design (5).png
    - assets/Untitled design.png
    - assets/Beer/Ale/Bottle/
    - assets/Beer/Ale/Can/
    - assets/Beer/Ale/Draft/
    - assets/Beer/Cider/Bottle/
    - assets/Beer/Cider/Can/
    - assets/Beer/Cider/Draft/
    - assets/Beer/Lager/Bottle/
    - assets/Beer/Lager/Can/
    - assets/Beer/Lager/Draft/
    - assets/Spirits/
    - assets/Spirits/Whiskey/Bourbon/
    - assets/Spirits/Whiskey/Canadian Whiskey/
    - assets/Spirits/Whiskey/Irish Whiskey/
    - assets/Spirits/Whiskey/Scotch/
    - assets/Spirits/Whiskey/Rye Whiskey/
    - assets/Spirits/Whiskey/Tennessee Whiskey/
    - assets/Spirits/Brandy/
    - assets/Spirits/Brandy/Cognac/
    - assets/Spirits/Gin/
    - assets/Spirits/Rum/Dark/
    - assets/Spirits/Rum/Light/
    - assets/Spirits/Tequila/Anejo/
    - assets/Spirits/Tequila/Blanco/
    - assets/Spirits/Tequila/Reposado/
    - assets/Spirits/Tequila/Gold/
    - assets/Spirits/Tequila/Mezcal/
    - assets/Spirits/Liqueurs/
    - assets/Spirits/Vodka/
    - assets/Drink Category Photos/Spirits/Whiskey/
    - assets/Drink Category Photos/Spirits/Brandy/
    - assets/Drink Category Photos/Spirits/Rum/
    - assets/Drink Category Photos/Spirits/Tequila/
    - assets/Drink Category Photos/Spirits/
    - assets/Drink Category Photos/Cocktails/
    - assets/Drink Category Photos/Beer/
    - assets/Drink Category Photos/Beer/Beer/
    - assets/Drink Category Photos/Wine/
    - assets/Drink Category Photos/Wine/Red Wine/
    - assets/Drink Category Photos/Wine/White Wine/
    - assets/Drink Category Photos/Seltzer/
    - assets/Drink Category Photos/Mixers/
    - assets/Drink Category Photos/Other/
    - assets/Cocktails/Brandy/
    - assets/Cocktails/Gin/
    - assets/Cocktails/Rum/
    - assets/Cocktails/Tequila/
    - assets/Cocktails/Wine/
    
    