name: drink_dictionary
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Untitled design (5).png
    - assets/Untitled design.png
    - assets/Drink Category Photos/Spirits/Whiskey.png
    - assets/Whiskey/Bourbon/Buffalo Trace.png
    - assets/Whiskey/Bourbon/
    - assets/Whiskey/Irish Whiskey/
    - assets/Drink Category Photos/Spirits/
    - assets/Drink Category Photos/Cocktails/
    - assets/Drink Category Photos/Beer/
    - assets/Drink Category Photos/Wine/
    - assets/Drink Category Photos/Seltzer/
    - assets/Tequila/Blanco/
    - assets/Brandy/Cognac/
    - assets/Cocktails/Brandy/
    - assets/Cocktails/Gin/
    - assets/Cocktails/Rum/
    - assets/Cocktails/Tequila/
    - assets/Cocktails/Wine/
    
    