name: drink_dictionary
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  azlistview: ^2.0.0
  firebase_auth: ^4.15.2
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_typeahead: ^5.0.1
  google_fonts: ^6.1.0
  searchfield: ^0.9.0
  substring_highlight: ^1.0.33

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/Untitled design (5).png
    - assets/Untitled design.png
    - assets/Beer/Ale/Bottle/
    - assets/Beer/Ale/Can/
    - assets/Beer/Ale/Draft/
    - assets/Beer/Cider/Bottle/
    - assets/Beer/Cider/Can/
    - assets/Beer/Cider/Draft/
    - assets/Beer/Lager/Bottle/
    - assets/Beer/Lager/Can/
    - assets/Beer/Lager/Draft/
    - assets/Spirits/
    - assets/Spirits/Whiskey/Bourbon/
    - assets/Spirits/Whiskey/Canadian Whiskey/
    - assets/Spirits/Whiskey/Irish Whiskey/
    - assets/Spirits/Whiskey/Scotch/
    - assets/Spirits/Whiskey/Rye Whiskey/
    - assets/Spirits/Whiskey/Tennessee Whiskey/
    - assets/Spirits/Brandy/
    - assets/Spirits/Brandy/Cognac/
    - assets/Spirits/Gin/
    - assets/Spirits/Rum/Dark/
    - assets/Spirits/Rum/Light/
    - assets/Spirits/Tequila/Anejo/
    - assets/Spirits/Tequila/Blanco/
    - assets/Spirits/Tequila/Reposado/
    - assets/Spirits/Tequila/Gold/
    - assets/Spirits/Tequila/Mezcal/
    - assets/Spirits/Liqueurs/
    - assets/Spirits/Vodka/
    - assets/Drink Category Photos/Spirits/Whiskey/
    - assets/Drink Category Photos/Spirits/Brandy/
    - assets/Drink Category Photos/Spirits/Rum/
    - assets/Drink Category Photos/Spirits/Tequila/
    - assets/Drink Category Photos/Spirits/
    - assets/Drink Category Photos/Cocktails/
    - assets/Drink Category Photos/Beer/
    - assets/Drink Category Photos/Beer/Beer/
    - assets/Drink Category Photos/Wine/
    - assets/Drink Category Photos/Wine/Red Wine/
    - assets/Drink Category Photos/Wine/White Wine/
    - assets/Drink Category Photos/Seltzers/
    - assets/Drink Category Photos/Mixers/
    - assets/Drink Category Photos/Other/
    - assets/Cocktails/Brandy/
    - assets/Cocktails/Gin/
    - assets/Cocktails/Rum/
    - assets/Cocktails/Tequila/
    - assets/Cocktails/Wine/
    - assets/loganriedley_design_a_iOS_app_icon_with_a_flat_white_cocktail_g_f6705fca-d2cf-45c4-a970-068ddc724de9.png
    