import 'package:flutter/material.dart';

class Drink {
  final String drinkName;
  final AssetImage drinkImage;
  final String? category;
  final String? subcategory;
  final String? tertiary;
  final String? drinkDescription;

  const Drink({
    required this.drinkName,
    required this.drinkImage,
    this.category,
    this.subcategory,
    this.tertiary,
    this.drinkDescription,
  });
}

List<Drink> drinks = [
  const Drink(
    drinkImage:
        AssetImage('assets/Spirits/Whiskey/Bourbon/Bulleit Bourbon.png'),
    drinkName: 'Bulleit Bourbon',
    category: 'Spirits',
    subcategory: 'Whiskey',
    tertiary: 'Bourbon',
    drinkDescription: '',
  ),
  const Drink(
    drinkImage: AssetImage('assets/Spirits/Whiskey/Bourbon/Blanton\'s.png'),
    drinkName: 'Blanton\'s',
    category: 'Spirits',
    subcategory: 'Whiskey',
    tertiary: 'Bourbon',
    drinkDescription: '',
  ),
  const Drink(
    drinkImage: AssetImage('assets/Spirits/Whiskey/Bourbon/Buffalo Trace.png'),
    drinkName: 'Buffalo Trace',
    category: 'Spirits',
    subcategory: 'Whiskey',
    tertiary: 'Bourbon',
    drinkDescription: '',
  ),
  const Drink(
    drinkImage:
        AssetImage('assets/Spirits/Whiskey/Bourbon/Woodford Reserve.png'),
    drinkName: 'Woodford Reserve',
    category: 'Spirits',
    subcategory: 'Whiskey',
    tertiary: 'Bourbon',
    drinkDescription: '',
  ),
  const Drink(
    drinkImage: AssetImage('assets/Spirits/Whiskey/Bourbon/Jim Beam.png'),
    drinkName: 'Jim Beam',
    category: 'Spirits',
    subcategory: 'Whiskey',
    tertiary: 'Bourbon',
    drinkDescription: '',
  ),
  const Drink(
    drinkImage: AssetImage('assets/Spirits/Whiskey/Bourbon/Knob Creek.png'),
    drinkName: 'Knob Creek',
    category: 'Spirits',
    subcategory: 'Whiskey',
    tertiary: 'Bourbon',
    drinkDescription: '',
  ),
  const Drink(
    drinkImage: AssetImage('assets/Spirits/Whiskey/Bourbon/Old Forester.png'),
    drinkName: 'Old Forester',
    category: 'Spirits',
    subcategory: 'Whiskey',
    tertiary: 'Bourbon',
    drinkDescription: '',
  ),
  const Drink(
    drinkImage:
        AssetImage('assets/Spirits/Whiskey/Irish Whiskey/Proper Twelve.png'),
    drinkName: 'Proper Twelve',
    category: 'Spirits',
    subcategory: 'Whiskey',
    tertiary: 'Irish Whiskey',
    drinkDescription: '',
  ),
  const Drink(
    drinkImage:
        AssetImage('assets/Spirits/Whiskey/Irish Whiskey/Tullamore D.E.W..png'),
    drinkName: 'Tullamore D.E.W.',
    category: 'Spirits',
    subcategory: 'Whiskey',
    tertiary: 'Irish Whiskey',
    drinkDescription: '',
  ),
  const Drink(
    drinkImage: AssetImage('assets/Spirits/Brandy/Cognac/Hennessy XO.png'),
    drinkName: 'Hennessy XO',
    category: 'Spirits',
    subcategory: 'Brandy',
    tertiary: 'Cognac',
    drinkDescription: '',
  ),
  const Drink(
    drinkImage:
        AssetImage('assets/Spirits/Tequila/Blanco/Casamigos Blanco.png'),
    drinkName: 'Casamigos Blanco',
    category: 'Spirits',
    subcategory: 'Tequila',
    tertiary: 'Blanco',
    drinkDescription: '',
  ),
  const Drink(
    drinkImage:
        AssetImage('assets/Spirits/Tequila/Blanco/Jose Cuervo Blanco.png'),
    drinkName: 'Jose Cuervo Blanco',
    category: 'Spirits',
    subcategory: 'Tequila',
    tertiary: 'Blanco',
    drinkDescription: '',
  ),
  const Drink(
    drinkImage: AssetImage('assets/Spirits/Tequila/Blanco/Patron Blanco.png'),
    drinkName: 'Patron Blanco',
    category: 'Spirits',
    subcategory: 'Tequila',
    tertiary: 'Blanco',
    drinkDescription: '',
  ),
  const Drink(
    drinkImage: AssetImage('assets/Cocktails/Brandy/Sazerac.png'),
    drinkName: 'Sazerac',
    category: 'Cocktails',
    subcategory: 'brandy',
    tertiary: '',
    drinkDescription: '',
  ),
  const Drink(
    drinkImage: AssetImage('assets/Cocktails/Brandy/Sidecar.png'),
    drinkName: 'Sidecar',
    category: 'Cocktails',
    subcategory: 'brandy',
    tertiary: '',
    drinkDescription: '',
  ),
  const Drink(
    drinkImage: AssetImage('assets/Cocktails/Gin/French 75.png'),
    drinkName: 'French 75',
    category: 'Cocktails',
    subcategory: 'gin',
    tertiary: '',
    drinkDescription: '',
  ),
  const Drink(
    drinkImage: AssetImage('assets/Cocktails/Gin/Gimlet.png'),
    drinkName: 'Gimlet',
    category: 'Cocktails',
    subcategory: 'gin',
    tertiary: '',
    drinkDescription: '',
  ),
  const Drink(
    drinkImage: AssetImage('assets/Cocktails/Gin/Negroni.png'),
    drinkName: 'Negroni',
    category: 'Cocktails',
    subcategory: 'gin',
    tertiary: '',
    drinkDescription: '',
  ),
  const Drink(
    drinkImage: AssetImage('assets/Cocktails/Rum/Bahama Mama.png'),
    drinkName: 'Bahama Mama',
    category: 'Cocktails',
    subcategory: 'rum',
    tertiary: '',
    drinkDescription: '',
  ),
  const Drink(
    drinkImage: AssetImage('assets/Cocktails/Rum/Daiquiri.png'),
    drinkName: 'Daiquiri',
    category: 'Cocktails',
    subcategory: 'rum',
    tertiary: '',
    drinkDescription: '',
  ),
  const Drink(
    drinkImage: AssetImage('assets/Cocktails/Rum/Dark n\' Stormy.png'),
    drinkName: 'Dark n\' Stormy',
    category: 'Cocktails',
    subcategory: 'rum',
    tertiary: '',
    drinkDescription: '',
  ),
  const Drink(
    drinkImage: AssetImage('assets/Cocktails/Rum/Mai Tai.png'),
    drinkName: 'Mai Tai',
    category: 'Cocktails',
    subcategory: 'rum',
    tertiary: '',
    drinkDescription: '',
  ),
  const Drink(
    drinkImage: AssetImage('assets/Cocktails/Rum/Mojito.png'),
    drinkName: 'Mojito',
    category: 'Cocktails',
    subcategory: 'rum',
    tertiary: '',
    drinkDescription: '',
  ),
  const Drink(
    drinkImage: AssetImage('assets/Cocktails/Rum/Painkiller.png'),
    drinkName: 'Painkiller',
    category: 'Cocktails',
    subcategory: 'rum',
    tertiary: '',
    drinkDescription: '',
  ),
  const Drink(
    drinkImage: AssetImage('assets/Cocktails/Rum/Pina Colada.png'),
    drinkName: 'Pina Colada',
    category: 'Cocktails',
    subcategory: 'rum',
    tertiary: '',
    drinkDescription: '',
  ),
  const Drink(
    drinkImage: AssetImage('assets/Cocktails/Tequila/Margarita.png'),
    drinkName: 'Margarita',
    category: 'Cocktails',
    subcategory: 'tequila',
    tertiary: '',
    drinkDescription: '',
  ),
  const Drink(
    drinkImage: AssetImage('assets/Cocktails/Tequila/Paloma.png'),
    drinkName: 'Paloma',
    category: 'Cocktails',
    subcategory: 'tequila',
    tertiary: '',
    drinkDescription: '',
  ),
  const Drink(
    drinkImage: AssetImage('assets/Cocktails/Tequila/Tequila Sunrise.png'),
    drinkName: 'Tequila Sunrise',
    category: 'Cocktails',
    subcategory: 'tequila',
    tertiary: '',
    drinkDescription: '',
  ),
  const Drink(
    drinkImage: AssetImage('assets/Untitled design.png'),
    drinkName: 'Tito\'s and Soda',
    category: 'Cocktails',
    subcategory: 'vodka',
    tertiary: '',
    drinkDescription: '',
  ),
  const Drink(
    drinkImage: AssetImage('assets/Cocktails/Wine/Americano.png'),
    drinkName: 'Americano',
    category: 'Cocktails',
    subcategory: 'wine',
    tertiary: '',
    drinkDescription: '',
  ),
  const Drink(
    drinkImage: AssetImage('assets/Cocktails/Wine/Bellini.png'),
    drinkName: 'Bellini',
    category: 'Cocktails',
    subcategory: 'wine',
    tertiary: '',
    drinkDescription: '',
  ),
  const Drink(
    drinkImage: AssetImage('assets/Cocktails/Wine/Mimosa.png'),
    drinkName: 'Mimosa',
    category: 'Cocktails',
    subcategory: 'wine',
    tertiary: '',
    drinkDescription: '',
  ),
  const Drink(
    drinkName: 'Bud Light',
    drinkImage: AssetImage('assets/Beer/Lager/Bottle/Bud Light.png'),
    category: 'Beer',
    subcategory: 'Lager',
    tertiary: 'Bottle',
    drinkDescription: '',
  ),
  const Drink(
    drinkName: 'Budweiser',
    drinkImage: AssetImage('assets/Beer/Lager/Bottle/Budweiser.png'),
    category: 'Beer',
    subcategory: 'Lager',
    tertiary: 'Bottle',
    drinkDescription: '',
  ),
  const Drink(
    drinkName: 'Coors Light',
    drinkImage: AssetImage('assets/Beer/Lager/Bottle/Coors Light.png'),
    category: 'Beer',
    subcategory: 'Lager',
    tertiary: 'Bottle',
    drinkDescription: '',
  ),
  const Drink(
    drinkName: 'Dos Equis',
    drinkImage: AssetImage('assets/Beer/Lager/Bottle/Dos Equis.png'),
    category: 'Beer',
    subcategory: 'Lager',
    tertiary: 'Bottle',
    drinkDescription: '',
  ),
  const Drink(
    drinkName: 'Heineken',
    drinkImage: AssetImage('assets/Beer/Lager/Bottle/Heineken.png'),
    category: 'Beer',
    subcategory: 'Lager',
    tertiary: 'Bottle',
    drinkDescription: '',
  ),
  const Drink(
    drinkName: 'Corona',
    drinkImage: AssetImage('assets/Beer/Lager/Bottle/Corona.png'),
    category: 'Beer',
    subcategory: 'Lager',
    tertiary: 'Bottle',
    drinkDescription: '',
  ),
  const Drink(
    drinkName: 'Stella Artois',
    drinkImage: AssetImage('assets/Beer/Lager/Bottle/Stella Artois.png'),
    category: 'Beer',
    subcategory: 'Lager',
    tertiary: 'Bottle',
    drinkDescription: '',
  ),
  const Drink(
    drinkName: 'Michelob Ultra',
    drinkImage: AssetImage('assets/Beer/Lager/Bottle/Michelob Ultra.png'),
    category: 'Beer',
    subcategory: 'Lager',
    tertiary: 'Bottle',
    drinkDescription: '',
  ),
  const Drink(
    drinkName: 'Modelo',
    drinkImage: AssetImage('assets/Beer/Lager/Bottle/Modelo.png'),
    category: 'Beer',
    subcategory: 'Lager',
    tertiary: 'Bottle',
    drinkDescription: '',
  ),
  const Drink(
    drinkName: 'Pabst Blue Ribbon',
    drinkImage: AssetImage('assets/Beer/Lager/Bottle/Pabst Blue Ribbon.png'),
    category: 'Beer',
    subcategory: 'Lager',
    tertiary: 'Bottle',
    drinkDescription: '',
  ),
  const Drink(
    drinkName: 'Bud Light',
    drinkImage: AssetImage('assets/Beer/Lager/Can/Bud Light.png'),
    category: 'Beer',
    subcategory: 'Lager',
    tertiary: 'Can',
    drinkDescription: '',
  ),
  const Drink(
    drinkName: 'Pabst Blue Ribbon',
    drinkImage: AssetImage('assets/Beer/Lager/Can/Pabst Blue Ribbon.png'),
    category: 'Beer',
    subcategory: 'Lager',
    tertiary: 'Can',
    drinkDescription: '',
  ),
  const Drink(
    drinkName: 'Blue Moon',
    drinkImage: AssetImage('assets/Beer/Ale/Bottle/Blue Moon.png'),
    category: 'Beer',
    subcategory: 'Ale',
    tertiary: 'Bottle',
    drinkDescription: '',
  ),
  const Drink(
    drinkName: 'Guinness',
    drinkImage: AssetImage('assets/Beer/Ale/Bottle/Guinness.png'),
    category: 'Beer',
    subcategory: 'Ale',
    tertiary: 'Bottle',
    drinkDescription: '',
  ),
  const Drink(
    drinkName: 'Fat Tire',
    drinkImage: AssetImage('assets/Beer/Ale/Bottle/Fat Tire.png'),
    category: 'Beer',
    subcategory: 'Ale',
    tertiary: 'Bottle',
    drinkDescription: '',
  ),
  const Drink(
    drinkName: 'Kona Big Wave',
    drinkImage: AssetImage('assets/Beer/Ale/Bottle/Kona Big Wave.png'),
    category: 'Beer',
    subcategory: 'Ale',
    tertiary: 'Bottle',
    drinkDescription: '',
  ),
  const Drink(
    drinkName: 'Sierra Nevada Pale Ale',
    drinkImage: AssetImage('assets/Beer/Ale/Bottle/Sierra Nevada Pale Ale.png'),
    category: 'Beer',
    subcategory: 'Ale',
    tertiary: 'Bottle',
    drinkDescription: '',
  ),
  const Drink(
    drinkName: 'Guinness',
    drinkImage: AssetImage('assets/Beer/Ale/Can/Guinness.png'),
    category: 'Beer',
    subcategory: 'Ale',
    tertiary: 'Can',
    drinkDescription: '',
  ),
];
